string = str('Olá mundo')
inteiro = int(10)
Fluante = float(100.5)
complexo = complex( 1j )
Lista = list(('Maça','Morango'))
tupla = tuple(('A','B'))
rangee = range(6)
dicionario = dict(nome = 'Odemir', age = 29)
s3t = set(('A','B','C'))
frozens3t = frozenset(('A','B','C'))
Boleano = bool(5)
bytEs = bytes(5)
byteArray = bytearray(5)
MemoryView = memoryview( bytes(5))
from datetime import datetime
data = datetime.today()
type(string)