numero1 =float(input("Digite o número: "))
numero2 =float(input("Digite o número: "))
numero3 =float(input("Digite o número: "))
print(numero1+numero2+numero3)
print((numero1+numero2+numero3)/3)
print(numero1*numero2*numero3)